### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by AndreyRGW** [AG-w/sd-webui-smea#1]
```
*** Error loading script: sd-webui-smea.py
    Traceback (most recent call last):
      File "F:\WBC\automatic1111_dev\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\WBC\automatic1111_dev\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 879, in exec_module
      File "<frozen importlib._bootstrap_external>", line 1017, in get_code
      File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\WBC\automatic1111_dev\extensions\sd-webui-smea\scripts\sd-webui-smea.py", line 232
        return xl, dt, sigma_hat, **extra_args)
                                              ^
    SyntaxError: unmatched ')'

---
```

**Comment by AG-w** [comment]
oh, I didn't notice that line
I fixed it now

I'm still experimenting how sample work
