### ISSUE TITLE
[BUG]Cant use TCD and Sema By Koishi Star in Webui 1.9.3

### ISSUE THREAD

**Issue by sdbds** [AG-w/sd-webui-smea#4]
Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.1\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\sd-webui-aki-v4.1\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\sd-webui-aki-v4.1\modules\txt2img.py", line 109, in txt2img
        processed = processing.process_images(p)
      File "D:\sd-webui-aki-v4.1\modules\processing.py", line 845, in process_images
        res = process_images_inner(p)
      File "D:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 59, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "D:\sd-webui-aki-v4.1\modules\processing.py", line 981, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\sd-webui-aki-v4.1\modules\processing.py", line 1328, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "D:\sd-webui-aki-v4.1\modules\sd_samplers_kdiffusion.py", line 218, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\sd-webui-aki-v4.1\modules\sd_samplers_common.py", line 272, in launch_sampling
        return func()
      File "D:\sd-webui-aki-v4.1\modules\sd_samplers_kdiffusion.py", line 218, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\sd-webui-aki-v4.1\extensions\sd-webui-smea\scripts\sd-webui-smea.py", line 823, in sample_tcd_euler_a
        noise_sampler = default_noise_sampler(x) if noise_sampler is None else noise_sampler
    NameError: name 'default_noise_sampler' is not defined

**Comment by AG-w** [comment]
oh, I forgot default_noise_sampler, lel
I just added it

**Comment by sdbds** [comment]
OK now
